{{- if .Values.hostname }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hostname
spec:
  schedule: {{ default "*/1 * * * *" .Values.hostnameCron.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          hostPID: true
          restartPolicy: OnFailure
          containers:
            - name: hostname
              image: {{ default "alpine:3.19" .Values.hostnameCron.image | quote }}
              imagePullPolicy: IfNotPresent
              securityContext:
                privileged: true
              env:
                - name: HOSTNAME_TARGET
                  value: {{ .Values.hostname | quote }}
              command:
                - /bin/sh
                - -c
                - |
                  apk add --no-cache util-linux >/dev/null
                  nsenter --target 1 --uts --mount -- /bin/sh -c "hostname \"$HOSTNAME_TARGET\"; echo \"$HOSTNAME_TARGET\" >/etc/hostname"
{{- end }}
