#!/usr/bin/env python3
import datetime
import time
import http.client
import ssl
from pathlib import Path
import subprocess

PAGES_HOST = 'oogy.github.io'
GH_HOST = 'github.com'

if __name__ == '__main__':
    serial_path = '/sys/class/dmi/id/product_serial'
    with open(serial_path, 'r') as product_serial:
        serial = product_serial.read()

    while True:
        print(f"Hello @ {datetime.datetime.now()} from {serial}")

        unverified_context = ssl._create_unverified_context()
        pages_conn = http.client.HTTPSConnection(PAGES_HOST, context=unverified_context)
        gh_conn = http.client.HTTPSConnection(GH_HOST, context=unverified_context)

        pages_conn.request("GET", f"/microcloud/inventory/{serial}".strip())
        import_images = pages_conn.getresponse().read().decode('utf-8').strip().split('\n')

        for image in import_images:
            image_name, image_tag = image.split('_')

            versioned_directory = Path(f"/var/lib/portables/{image_name}.raw.v")
            image_path = Path(f"/var/lib/portables/{image_name}.raw.v/{image_name}_{image_tag}.raw")

            image_url = f"https://{GH_HOST}/Oogy/microcloud/releases/download/v{image_tag}/{image_name}_{image_tag}.raw.xz"

            is_attached = subprocess.run(f"portablectl is-attached {image_name}".split(), text=True, check=True, capture_output=True).stdout.strip()

            if not versioned_directory.exists():
                print(f"{versioned_directory} missing, creating")
                versioned_directory.mkdir(parents=True)

            if not image_path.exists():
                print(f"Importing image {image} from {image_url}")
                import_command = f"importctl pull-raw -P --verify=no {image_url}"

                import_path = Path(f"/var/lib/portables/{image_name}_{image_tag}.raw")

                try:
                    subprocess.run(import_command.split(), text=True, check=True)
                    import_path.rename(image_path)
                except subprocess.CalledProcessError as e:
                    print(f"Error, unable to import {image_url}: {e}")

                if is_attached == 'attached':
                    print(f"{image_name} attached, reattaching")
                    subprocess.run(f"portablectl reattach {image_name} --enable --now --profile=trusted".split())

            if is_attached == 'detached':
                print(f"{image_name} not attached, attaching")
                subprocess.run(f"portablectl attach {image_name} --enable --now --profile=trusted".split())

        time.sleep(10)
