#!/usr/bin/env python3
import datetime
import time
import http.client
import ssl

PAGES_HOST = 'oogy.github.io'

if __name__ == '__main__':
    serial_path = '/sys/class/dmi/id/product_serial'
    with open(serial_path, 'r') as product_serial:
        serial = product_serial.read()

    while True:
        print(f"Hello @ {datetime.datetime.now()} from {serial}")
        unverified_context = ssl._create_unverified_context()
        conn = http.client.HTTPSConnection(PAGES_HOST, context=unverified_context)
        conn.request("GET", f"/microcloud/inventory/{serial}".strip(), headers={"Host": PAGES_HOST})
        import_images = conn.getresponse().read().decode('utf-8').strip().split('\n')
        for image in import_images:
            print(f"Importing image {image}")
        time.sleep(10)
