csi-driver-nfs:
  controller:
    runOnMaster: false
    runOnControlPlane: true
    nodeSelector:
      kubernetes.io/os: linux
      node-role.kubernetes.io/control-plane: "true"
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
  kubeletDir: /var/lib/k0s/kubelet
