csi-driver-nfs:
  controller:
    runOnMaster: false
    runOnControlPlane: true
    nodeSelector:
      kubernetes.io/os: linux
      node-role.kubernetes.io/control-plane: "true"
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
  kubeletDir: /var/lib/k0s/kubelet
  storageClass:
    create: true
    name: nfs-csi
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
    server: 127.0.0.1
    share: /opt/microcloud/nfs/data
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    mountOptions:
      - nfsvers=4
