{{- if .Values.nfsSetupEnabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nfs-setup
  namespace: {{ default .Release.Namespace .Values.nfsSetupNamespace }}
data:
  nfs.sh: |
    #!/usr/bin/env bash

    set -x

    NFS_USER="{{ .Values.nfsSetupUser }}"
    NFS_GROUP="{{ .Values.nfsSetupGroup }}"
    EXPORT_PATH="{{ .Values.nfsSetupExportPath }}"
    MOUNT_PATH="{{ .Values.nfsSetupMountPath }}"
    CONF_PATH="/etc/nfs.conf.d/{{ .Values.nfsSetupConfName }}.conf"
    EXPORT_OPTS="{{ .Values.nfsSetupExportOptions }}"

    apt -y install nfs-kernel-server nfs-common rpcbind

    if systemctl is-active nfs-kernel-server -q; then
      systemctl stop nfs-kernel-server.service
    fi

    if systemctl is-active rpcbind.service -q; then
      systemctl stop rpcbind.service
    fi

    if systemctl is-active rpcbind.socket -q; then
      systemctl stop rpcbind.socket
    fi

    if [ "$(systemctl is-enabled rpcbind.service)" != "masked" ]; then
      systemctl mask rpcbind.service
    fi

    if [ "$(systemctl is-enabled rpcbind.socket)" != "masked" ]; then
      systemctl mask rpcbind.socket
    fi

    if [ ! -f "${CONF_PATH}" ]; then
      tee "${CONF_PATH}" <<-EOF
	[nfsd]
	vers3=n
	host=127.0.0.1

	[mountd]
	manage-gids=y
	port=42069
	EOF
    fi

    if ! id "${NFS_USER}"; then
      useradd -m "${NFS_USER}"
    fi

    if [ -n "${NFS_GROUP}" ] && ! getent group "${NFS_GROUP}" >/dev/null 2>&1; then
      groupadd "${NFS_GROUP}"
    fi

    if [ -n "${NFS_GROUP}" ]; then
      usermod -g "${NFS_GROUP}" "${NFS_USER}"
    fi

    if [ ! -d "${EXPORT_PATH}" ]; then
      mkdir -p "${EXPORT_PATH}"
      chown -R "${NFS_USER}:${NFS_GROUP:-${NFS_USER}}" "$(dirname "${EXPORT_PATH}")"
      chown -R "${NFS_USER}:${NFS_GROUP:-${NFS_USER}}" "${EXPORT_PATH}"
    fi

    if [ ! -d "${MOUNT_PATH}" ]; then
      mkdir -p "${MOUNT_PATH}"
      chown -R "${NFS_USER}:${NFS_GROUP:-${NFS_USER}}" "$(dirname "${MOUNT_PATH}")"
      chown -R "${NFS_USER}:${NFS_GROUP:-${NFS_USER}}" "${MOUNT_PATH}"
    fi

    if ! grep -q "${EXPORT_PATH}" /etc/exports; then
      tee /etc/exports <<-EOF
	${EXPORT_PATH} ${EXPORT_OPTS}
	EOF
    fi

    if ! exportfs -s | grep "${EXPORT_PATH}" -q; then
      exportfs -a
    fi

    if ! systemctl is-active nfs-kernel-server.service -q; then
      systemctl restart nfs-kernel-server.service
    fi
{{- end }}
